DROP TABLE  IF EXISTS ADDRESS CASCADE;
DROP TABLE  IF EXISTS COORDINATES CASCADE;
DROP TABLE  IF EXISTS LOCATION CASCADE;
DROP TABLE IF EXISTS  ORGANIZATION CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
