CREATE TABLE IF NOT EXISTS COORDINATES(
	ID SERIAL PRIMARY KEY,
	X REAL NOT NULL,
	Y DOUBLE PRECISION NOT NULL
);


CREATE TABLE IF NOT EXISTS LOCATION(
	ID SERIAL PRIMARY KEY,
	X BIGINT NOT NULL,
	Y INTEGER NOT NULL,
	NAME TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ADDRESS(
	ID SERIAL PRIMARY KEY,
	STREET TEXT NOT NULL,
	LOCATION_ID INTEGER NOT NULL REFERENCES LOCATION(ID)
);

CREATE TABLE IF NOT EXISTS USERS(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(20) UNIQUE NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORGANIZATION(
	ID SERIAL PRIMARY KEY,
	NAME TEXT NOT NULL CHECK (NAME <> ''),
	COORDINATES_ID INTEGER NOT NULL REFERENCES COORDINATES(ID),
	CREATION_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	ANNUAL_TURNOVER BIGINT NOT NULL CHECK (ANNUAL_TURNOVER > 0),
	ORG_TYPE TEXT NOT NULL,
	ADDRESS_ID INTEGER REFERENCES ADDRESS(ID),
	AUTHOR_ID INTEGER REFERENCES USERS(ID)
);

